import { type PropsWithChildren } from "react";
import Head from "next/head";
import Nav from "../Molecules/Nav";
import Footer from "../Molecules/Footer";

const PageLayout = ({ children }: PropsWithChildren) => {
  return (
    <>
      <Head>
        <title>Prop Doc</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="] flex min-h-screen flex-col items-center bg-light">
        <Nav />
        {children}
        <Footer />
      </main>
    </>
  );
};

export default PageLayout;
